### ISSUE TITLE
[FEAT/bc001/yerimee] 작업대상재 편성

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#1]
## 💡 Feature Issue

- **이슈 제목**: 빠른 개발과 설정을 위한 테스트 개발
- **요약**: 초기 셋팅을 위해 필요한 것들을 빠르게 파악하기 위해 REST API 로 작업대상재 추출 도메인 로직 작성 
- **기능 설명**: Mock 데이터를 활용하여 추출기준 및 에러기준을 통해 작업대상재 추출
- **배경 및 맥락**: 

## 🌿  To-do

- [x] 작업대상재, 추출기준, 에러기준 엔티티 작성 -> 테스트 작성
- [ ] 추출 로직 작성 
- [x] Swagger 테스트
- [x] gateway 테스트 
- [ ] 기타 추가 설정 파악하기 

## 📅 Timeline

- **시작일**: 2024-08-18
- **종료일**: 2024-08-19

## 👥 Assignees & Reviewers

- **할당자**: @yerimee82 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**: !! 테스트 개발입니다!! 설정 확인을 위한 테스트 개발입니다.
