### ISSUE TITLE
[FEAT/redis/yerimee] 재료 데이터 Redis 캐싱 

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#11]
## 💡 Feature Issue

- **이슈 제목**: 재료 데이터를 카프카로 전송합니다. 이를 레디스 서버에서 캐싱합니다. 
- **요약**: 레디스 설정 진행하기 
- **기능 설명**: 카프카로 받은 데이터를 캐싱 서버에 저장합니다. 중앙 캐싱 서비스를 설정합니다. 
- **배경 및 맥락**: 캐싱을 통한 성능 향상

## 🌿  To-do

- [x] 로컬 Redis 설정 
- [x] 카프카로 받은 데이터 저장
- [ ] 데이터 수정 시, 즉시 반영되도록

## 📅 Timeline

- **시작일**: 2024-08-30
- **종료일**: 2024-08-31
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 👥 Assignees & Reviewers

- **할당자**: @yerimee82 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:
