### ISSUE TITLE
[FEAT/reactiveRedis/yerimee] Redis 비동기식 저장 및 업데이트

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#14]
## 💡 Feature Issue

- **이슈 제목**: Redis 비동기식 저장 및 업데이트
- **요약**: 비동기식으로 카프카에서부터 데이터를 저장합니다. 
- **기능 설명**: cdc 로 데이터 변동 감지된 내용을 비동기식으로 redis 에 저장 및 업데이트 합니다. 해시 형태로 저장합니다. 
- **배경 및 맥락**: 기존에 동기식에서 비동기 식으로 전환. 아직 해시 형태로 저장 X. 기존 레디스 저장 방식 개선 

## 🌿  To-do

- [ ] 해시 형태 저장 메서드 생성
- [ ] 재료 서비스를 제네릭 서비스로 변경하여 사용
- [ ] 관제에 재료 데이터 전송
- [ ] 데이터 update 확인

## 📅 Timeline

- **시작일**: 2024-09-03
- **종료일**: 2024-09-06
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 🧩 Dependencies

- [ ] Dependency 1
- [ ] Dependency 2

## 👥 Assignees & Reviewers

- **할당자**: @yerimee82 
- **리뷰어**: @username

## 📌 Notes

- **참고 사항**:
