### ISSUE TITLE
[FEAT/setting/yerimee] Spring Rest Docs 설정

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#2]
## 💡 Feature Issue

- **이슈 제목**: Spring Rest Docs 설정 
- **요약**: API 관련 Docs 를 설정합니다. Spring Rest Docs + Swagger UI + gateway 조합입니다. 
- **기능 설명**: Spring REST Docs를 이용한 API 문서화 설정입니다. 
- **배경 및 맥락**:  Swagger는 애너테이션 기반으로 문서화하기 때문에 개발이 용이하지만, 
                               프로덕션 코드에 불필요한 코드가 포함될 수 있다는 단점이 있다. 따라서, Spring Rest Docs + Swagger UI 조합으로 
                               API 문서를 관리하고자 한다. 

## 🌿  To-do

- [ ] Spring Rest Docs Gateway 에 설정하기 
- [ ] Swagger UI 와 연결
- [ ] 문서화 배포 관리 

## 📅 Timeline

- **시작일**: 2024-08-22
- **종료일**: 2024-08-23
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 👥 Assignees & Reviewers

- **할당자**: @yerimee82 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:
