### ISSUE TITLE
[FEAT/scheduling/ash] 스케줄 화면 연결 API 및 서비스 개발

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-backend#26]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 화면 연결 API 및 서비스 개발
- **요약**: 스케줄 화면 연결 API 및 서비스 개발
- **기능 설명**: 스케줄 화면 연결 API 개발 ,  서비스 개발
- **배경 및 맥락**: 스케줄 화면 연결을 위한 API 개발 및 화면에 맞는 서비스 개발

## 🌿  To-do

- [x] 스케줄 모든 화면 (fs001,fs002,fs003,fs004) 연결
- [x] 스케줄 편성 엔티티 개발
- [x] 스케줄 이력 엔티티 개발
- [x] 서비스 개발
- [x] API 개발

## 📅 Timeline

- **시작일**: 2024-09-07
- **종료일**: 2024-09-09
- **마일스톤 이름**: 스케줄 화면 연결 API 및 서비스 개발
    - **목표**: 스케줄 화면 연결 API 및 관련 서비스, 엔터티 개발
    - **기한**: 2024-09-09
    - **관련 이슈**: #8

## 🧩 Dependencies

- [x] #8

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
