### ISSUE TITLE
[REFACTOR/scheduling/ash] DTO 형식 변경

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-backend#38]
## 💡 Feature Issue

- **이슈 제목**: DTO 형식 변경
- **요약**: API response DTO와 Redis와 통신할 DTO의 형식 변경
- **기능 설명**: API response DTO 으로 현재 DTO wrapping, Redis와 통신할 DTO의 형식 변경
- **배경 및 맥락**: Response DTO를 통해 모든 응답 형식 통일

## 🌿  To-do

- [x] MaterialDTO, TargetDTO, ScheduleDTO 세개로 분리
- [x] 세가지 DTO를 mapping할 compositeDTO 생성
- [x] Response DTO wrapping을 통해 응답 형식 통일

## 📅 Timeline

- **시작일**: 2024-09-11
- **종료일**: 2024-09-13
- **마일스톤 이름**: DTO refactoring
    - **목표**: API response DTO와 Redis와 통신할 DTO의 형식 변경
    - **기한**: 2024-09-13
    - **관련 이슈**: #8 , #26

## 🧩 Dependencies

- [x] #8
- [x] #26

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
