### ISSUE TITLE
[FEAT/flow-merge/yerimee] Redis 접근 리팩토링 및 스케쥴 연결

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#48]
## 💡 Feature Issue

- **이슈 제목**: Redis 에 접근해서 데이터 가져오는 것을 리팩토링 진행합니다. 또 스케쥴에 작업대상재 데이터를 불러옵니다. 
- **요약**: 리팩토링 및 스케쥴 연결하여 한 플로우 진행
- **기능 설명**: 
- **배경 및 맥락**: 

## 🌿  To-do

- [ ] Redis 접근 리팩토링
- [ ] 스케쥴 로직에 작업대상재 연결
- [ ] 스케쥴 결과 레디스 저장

## 📅 Timeline

- **시작일**: 2024-09-14
- **종료일**: 2024-09-15
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

- [ ] Dependency 1
- [ ] Dependency 2

## 👥 Assignees & Reviewers

- **할당자**: @username
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:
