### ISSUE TITLE
[Refactor/scheduling/ash] schedule 서비스 동작 확인 및 수정

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-backend#64]
## 💡 Feature Issue

- **이슈 제목**: schedule 서비스의 기능 세부 구현 및 동작 확인 및 수정
- **요약**: schedule 서비스의 기능 세부 구현, 동작 수정
- **기능 설명**: API 동작 확인, schedule 서비스의 기능 세부 구현, 동작 수정
- **배경 및 맥락**: API 동작 확인, schedule 서비스의 기능 세부 구현, 동작 수정

## 🌿  To-do

- [x] API 동작 확인
- [x] schedule 서비스의 기능 세부 구현
- [x] 에러있는 부분의 schedule 서비스 동작 수정

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

- [x] #61 

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
