### ISSUE TITLE
[FEAT/operation/yerimee] 코일 작업 진행 및 컬럼 값 변경 후 카프카 전송

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-backend#66]
## 💡 Feature Issue

- **이슈 제목**: 작업지시서를 토대로 코일 값 변경을 시작합니다.
- **요약**: 임의 작업 매커니즘 작성.
- **기능 설명**: 근데 스케쥴 대상재 엔티티 수정 필요 
- **배경 및 맥락**: 

## 🌿  To-do

- [ ] 스케쥴 엔티티 수정
- [ ] 작업지시서 변경 확인
- [ ] 보급 요구, 작업 현황 등 체크

## 📅 Timeline

- **시작일**: 2024-09-21
- **종료일**: 2024-09-22
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 
    - **관련 이슈**: 

## 🧩 Dependencies

- [ ] Dependency 1
- [ ] Dependency 2

## 👥 Assignees & Reviewers

- **할당자**: @username
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:
